name: Create Release
permissions:
  contents: write
  packages: write

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Create Release Archive
      run: |
        # Create release directory
        mkdir -p release/UltimateLoot
        
        # Copy addon files (exclude git and dev files)
        cp -r Core/ Lib/ Locales/ Modules/ Settings/ UI/ release/UltimateLoot/
        cp Init.lua UltimateLoot.toc wow_stubs.lua release/UltimateLoot/
        
        # Create zip archive
        cd release
        zip -r UltimateLoot-${{ github.ref_name }}.zip UltimateLoot/
    
    - name: Extract Changelog
      id: changelog
      run: |
        # Extract version-specific changelog
        VERSION=${{ github.ref_name }}
        VERSION_NO_V=${VERSION#v}
        
        # Get changelog section for this version (improved to handle edge cases)
        awk "/## \[${VERSION_NO_V}\]/{flag=1; next} /## \[/{flag=0} flag" CHANGELOG.md > release_notes.md
        
        # If no specific version found, use a default message
        if [ ! -s release_notes.md ]; then
          echo "Release ${VERSION}" > release_notes.md
          echo "" >> release_notes.md
          echo "See [CHANGELOG.md](CHANGELOG.md) for detailed changes." >> release_notes.md
        fi
        
        # Set output for release notes
        echo "notes<<EOF" >> $GITHUB_OUTPUT
        cat release_notes.md >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: UltimateLoot ${{ github.ref_name }}
        body: ${{ steps.changelog.outputs.notes }}
        draft: false
        prerelease: false
        files: ./release/UltimateLoot-${{ github.ref_name }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 